[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "server"
  external_node_modules = ["lightningcss", "@babel/core", "@babel/preset-typescript", "tsx", "esbuild", "instagram-url-direct"]
  node_bundler = "esbuild"
  included_files = ["node_modules/instagram-url-direct/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
